---
# Ansible Inventory for DEC
all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: "{{ ansible_playbook_python }}"

  children:
    windows:
      hosts:
        localhost:
      vars:
        ansible_shell_type: powershell
        ansible_become_method: runas
        ansible_become_user: Administrator

    linux:
      hosts:
        localhost:
      vars:
        ansible_become_method: sudo
        ansible_become_user: root
